### ISSUE TITLE
Quoted strings don't get ranked

### ISSUE THREAD

**Issue by hbillings** [NUKnightLab/cityhallmonitor#143]
"sale of city-owned property" sets the `is_ranked` value to `false`, but if you unquote it, it is `true`. Wat.

**Comment by JoeGermuska** [comment]
this is because it goes through a different search path which does not, in fact, result in relevance values being returned.

I'm inclined to disable exact quoted string matching, which is also painfully slow. I guess we could alternatively tokenize the quoted string and search for the terms in it conventionally, in addition to the exact string matching. But the ranker would not necessarily take the exact string match into account by returning a higher rank for those documents than others which had the same words in the same quantity but not "together" (tbh i have no idea how smart the rank algorithm is...)

**Comment by hbillings** [comment]
Ahh...we should change the example searches if we're going to do that, then. Could we just strip out the quotes so that the search returns something (and maybe make a note that we did that in the return)?

**Comment by JoeGermuska** [comment]
Closing. Essentially fixed by #145.
