### ISSUE TITLE
Determine if/how often matters have multiple documents

### ISSUE THREAD

**Issue by hbillings** [NUKnightLab/cityhallmonitor#49]

**Comment by jywsn** [comment]
There are...

1073 Matters with more than 1 MatterAttachment.
22 with more than 2
5 with more than 3
1 with more then 4

**Comment by jywsn** [comment]
Here is an example of 5 attachments connected to a single matter:
https://cityhallmonitor.knightlab.com/admin/cityhallmonitor/matterattachment/?q=47133

(Alternatively, login to the admin, goto MatterAttachments, and search for 47133)

**Comment by scott2b** [comment]
So if, e.g. you search for the following in the UI: Facilities lease and use agreement with Signature Flight Support Corp. at Midway International Airport

You can see how results are grouped, but there is not really any indicator of grouping. Since the titles of the search results are actually the matter titles, I think we would just want to show the title once and then links to all the documents under that title.

**Comment by jywsn** [comment]
Agreed.

**Comment by scott2b** [comment]
Question answered and issue #58 created. Closing for now.
